// src/components/PhilosophySection.js
// Sección "Philosophy" — Versión Blanca (Premium/Brutalist)

import { animatePhilosophySection } from '../lib/motion.js';

const PILLARS = [
  {
    id: 'pillar-quality',
    icon: `<svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="square"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg>`,
    label: 'Elite Quality',
    title: 'Third-Party\nTested',
    description: 'Every batch independently verified. Pharmaceutical-grade purity. No fillers, no shortcuts.',
  },
  {
    id: 'pillar-formula',
    icon: `<svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="square"><path d="M9 3H5a2 2 0 0 0-2 2v4m6-6h10a2 2 0 0 1 2 2v4M9 3v18m0 0h10a2 2 0 0 0 2-2v-4M9 21H5a2 2 0 0 1-2-2v-4m0 0h18"/></svg>`,
    label: 'Clinical Formulas',
    title: 'Clinically\nDosed',
    description: 'Every ingredient at the exact dose proven by science. No proprietary blends. Full transparency.',
  },
  {
    id: 'pillar-advisor',
    icon: `<svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="square"><path d="M12 2a10 10 0 1 0 10 10H12V2z"/><path d="M12 2a10 10 0 0 1 10 10"/><path d="M12 12l4-4"/></svg>`,
    label: 'AI Advisory',
    title: 'Your Personal\nTrainer',
    description: 'Personalized training and nutrition plans generated by AI. Built around your body. Your goals.',
  },
];

const TICKER_TEXT = [
  'CLINICAL DOSES',
  'NO FILLERS',
  'IRON FORGED',
  'MAXIMUM POWER',
  'THIRD-PARTY TESTED',
  'NO EXCUSES',
  'ELITE FORMULAS',
  'YOUR LEGACY STARTS HERE',
].map(t => `<span class="ticker-item">${t}</span><span class="ticker-sep text-[#e62429] mx-6">·</span>`).join('');

export const PhilosophySection = () => `
  <section
    id="philosophy"
    class="relative w-full bg-white dark:bg-black flex flex-col justify-between overflow-hidden transition-colors duration-300"
    style="height: 100dvh; min-height: 100vh;"
  >

    <!-- Línea decorativa superior -->
    <div class="absolute top-0 left-0 right-0 h-[1px] bg-gradient-to-r from-transparent via-[#e62429] to-transparent opacity-40"></div>

    <!-- ── TICKER MARQUEE ──────────────────────────────────────────────── -->
    <div class="w-full overflow-hidden border-b border-black/5 dark:border-white/5 py-4 flex-shrink-0 mt-16">
      <div class="flex whitespace-nowrap animate-marquee text-[11px] font-black tracking-[0.3em] uppercase text-black/40 dark:text-white/40">
        ${TICKER_TEXT}${TICKER_TEXT}
      </div>
    </div>

    <!-- ── FRASE CENTRAL ──────────────────────────────────────────────── -->
    <div class="flex-1 flex items-center justify-center px-6 sm:px-12 lg:px-20">
      <div id="philosophy-quote" class="text-center max-w-5xl opacity-0">

        <!-- Label rojo -->
        <p class="text-[#e62429] font-black uppercase tracking-[0.4em] text-[10px] sm:text-xs mb-6">
          The BitIron Manifesto
        </p>

        <!-- La frase brutal -->
        <h2
          class="font-black uppercase text-black dark:text-white leading-[0.9] tracking-tighter"
          style="font-size: clamp(2.8rem, 8vw, 110px);"
        >
          Not for<br/>
          <span class="text-[#e62429]">the weak.</span><br/>
          Built for<br/>
          champions.
        </h2>

        <!-- Descripción corta debajo -->
        <p class="mt-8 text-black/40 dark:text-white/40 text-xs sm:text-sm font-bold uppercase tracking-[0.25em] max-w-xl mx-auto leading-relaxed">
          Supplements engineered with science. Plans built by AI.
          Results measured in the mirror.
        </p>

      </div>
    </div>

    <!-- ── 3 PILARES ──────────────────────────────────────────────────── -->
    <div class="w-full border-t border-black/5 dark:border-white/5 flex-shrink-0">
      <div class="max-w-7xl mx-auto grid grid-cols-1 sm:grid-cols-3 divide-y sm:divide-y-0 sm:divide-x divide-black/5 dark:divide-white/5">

        ${PILLARS.map(({ id, icon, label, title, description }) => `
          <div
            id="${id}"
            class="group flex flex-col gap-3 px-8 py-8 opacity-0
                   transition-colors duration-300 hover:bg-black/[0.02] dark:hover:bg-white/[0.02] cursor-default"
          >
            <div class="text-[#e62429]">${icon}</div>
            <p class="text-black/30 dark:text-white/30 text-[9px] font-black uppercase tracking-[0.35em]">${label}</p>
            <h3 class="font-black uppercase text-black dark:text-white leading-tight text-lg sm:text-xl">
              ${title.replace('\n', '<br/>')}
            </h3>
            <p class="text-black/40 dark:text-white/40 text-xs leading-relaxed max-w-xs">${description}</p>
          </div>
        `).join('')}

      </div>
    </div>

    <!-- Línea decorativa inferior -->
    <div class="absolute bottom-0 left-0 right-0 h-[1px] bg-gradient-to-r from-transparent via-black/10 dark:via-white/10 to-transparent"></div>

  </section>
`;
